---
- name: update /etc/hostname
  hosts: remote_host
  become: yes
  tasks:
    - name: update /etc/hostname
      lineinfile:
        path: /etc/hostname
        regexp: '^.*$'
        line: "YuliiaDobosh-lab2"